import { NextRequest, NextResponse } from 'next/server';
import { getAuthUser, unauthorizedResponse } from '@/lib/server-auth';

// Paystack references generated by this app follow this pattern: enf_<digits>_<alphanumeric>
const REFERENCE_PATTERN = /^enf_\d+_[a-z0-9]+$/;

export async function GET(request: NextRequest) {
  // Require authenticated user — prevents unauthenticated enumeration
  const user = await getAuthUser(request);
  if (!user) return unauthorizedResponse();

  const reference = request.nextUrl.searchParams.get('reference');
  if (!reference) {
    return NextResponse.json({ error: 'Payment reference is required' }, { status: 400 });
  }

  // Validate reference format to prevent arbitrary lookups
  if (!REFERENCE_PATTERN.test(reference)) {
    return NextResponse.json({ error: 'Invalid reference format' }, { status: 400 });
  }

  try {
    const response = await fetch(
      `https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,
      {
        method: 'GET',
        headers: { Authorization: `Bearer ${process.env.PAYSTACK_SECRET_KEY}` },
      }
    );

    const data = await response.json();
    if (data.status && data.data?.status === 'success') {
      // Only return the fields the client actually needs
      return NextResponse.json({
        status: 'success',
        data: {
          reference: data.data.reference,
          amount: data.data.amount,
          currency: data.data.currency,
          paid_at: data.data.paid_at,
          plan: data.data.plan,
          metadata: data.data.metadata,
        },
      });
    }

    return NextResponse.json(
      { status: 'failed', message: 'Payment verification failed' },
      { status: 400 }
    );
  } catch {
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
